### ISSUE TITLE
Mobile Author Image Sizing

### ISSUE THREAD

**Issue by anon-zed** [KopfdesDaemons/blogtube#1]
When accessing the theme from mobile, 
the `<div class="blogtube_author_avatar">`
is scaled 

                                                  
![image0](https://github.com/KopfdesDaemons/blogtube/assets/153550936/90565024-09cc-4c0c-b587-2b99ef8f35ac)

**Comment by anon-zed** [comment]
I am unable to recreate it on desktop

**Comment by KopfdesDaemons** [comment]
Unfortunately I can't reproduce the problem either. Everything is right for me. If you can tell me more precisely when the problem occurs or what the cause is, I may be able to fix it. Otherwise I assume that the problem is not with the theme.
